# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class MessagePost(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id_sender: int=None, recipients_list: List[object]=None, text: str=None, date_delivery: str=None):  # noqa: E501
        """MessagePost - a model defined in Swagger

        :param id_sender: The id_sender of this MessagePost.  # noqa: E501
        :type id_sender: int
        :param recipients_list: The recipients_list of this MessagePost.  # noqa: E501
        :type recipients_list: List[object]
        :param text: The text of this MessagePost.  # noqa: E501
        :type text: str
        :param date_delivery: The date_delivery of this MessagePost.  # noqa: E501
        :type date_delivery: str
        """
        self.swagger_types = {
            'id_sender': int,
            'recipients_list': List[object],
            'text': str,
            'date_delivery': str
        }

        self.attribute_map = {
            'id_sender': 'id_sender',
            'recipients_list': 'recipients_list',
            'text': 'text',
            'date_delivery': 'date_delivery'
        }
        self._id_sender = id_sender
        self._recipients_list = recipients_list
        self._text = text
        self._date_delivery = date_delivery

    @classmethod
    def from_dict(cls, dikt) -> 'MessagePost':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Message_post of this MessagePost.  # noqa: E501
        :rtype: MessagePost
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id_sender(self) -> int:
        """Gets the id_sender of this MessagePost.

        Sender ID  # noqa: E501

        :return: The id_sender of this MessagePost.
        :rtype: int
        """
        return self._id_sender

    @id_sender.setter
    def id_sender(self, id_sender: int):
        """Sets the id_sender of this MessagePost.

        Sender ID  # noqa: E501

        :param id_sender: The id_sender of this MessagePost.
        :type id_sender: int
        """

        self._id_sender = id_sender

    @property
    def recipients_list(self) -> List[object]:
        """Gets the recipients_list of this MessagePost.

        List of recipients IDs  # noqa: E501

        :return: The recipients_list of this MessagePost.
        :rtype: List[object]
        """
        return self._recipients_list

    @recipients_list.setter
    def recipients_list(self, recipients_list: List[object]):
        """Sets the recipients_list of this MessagePost.

        List of recipients IDs  # noqa: E501

        :param recipients_list: The recipients_list of this MessagePost.
        :type recipients_list: List[object]
        """
        if recipients_list is None:
            raise ValueError("Invalid value for `recipients_list`, must not be `None`")  # noqa: E501

        self._recipients_list = recipients_list

    @property
    def text(self) -> str:
        """Gets the text of this MessagePost.

        Message text  # noqa: E501

        :return: The text of this MessagePost.
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text: str):
        """Sets the text of this MessagePost.

        Message text  # noqa: E501

        :param text: The text of this MessagePost.
        :type text: str
        """
        if text is None:
            raise ValueError("Invalid value for `text`, must not be `None`")  # noqa: E501

        self._text = text

    @property
    def date_delivery(self) -> str:
        """Gets the date_delivery of this MessagePost.

        date of delivery  # noqa: E501

        :return: The date_delivery of this MessagePost.
        :rtype: str
        """
        return self._date_delivery

    @date_delivery.setter
    def date_delivery(self, date_delivery: str):
        """Sets the date_delivery of this MessagePost.

        date of delivery  # noqa: E501

        :param date_delivery: The date_delivery of this MessagePost.
        :type date_delivery: str
        """
        if date_delivery is None:
            raise ValueError("Invalid value for `date_delivery`, must not be `None`")  # noqa: E501

        self._date_delivery = date_delivery
