# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Points(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, count: int=None):  # noqa: E501
        """Points - a model defined in Swagger

        :param count: The count of this Points.  # noqa: E501
        :type count: int
        """
        self.swagger_types = {
            'count': int
        }

        self.attribute_map = {
            'count': 'count'
        }
        self._count = count

    @classmethod
    def from_dict(cls, dikt) -> 'Points':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Points of this Points.  # noqa: E501
        :rtype: Points
        """
        return util.deserialize_model(dikt, cls)

    @property
    def count(self) -> int:
        """Gets the count of this Points.

        Lottery points of customer  # noqa: E501

        :return: The count of this Points.
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count: int):
        """Sets the count of this Points.

        Lottery points of customer  # noqa: E501

        :param count: The count of this Points.
        :type count: int
        """
        if count is None:
            raise ValueError("Invalid value for `count`, must not be `None`")  # noqa: E501

        self._count = count
