"""empty message

Revision ID: 17da34dfffc3
Revises: 
Create Date: 2021-11-29 12:41:44.152386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17da34dfffc3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id_message', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.Unicode(length=128), nullable=True),
    sa.Column('id_sender', sa.Integer(), nullable=True),
    sa.Column('id_receiver', sa.Integer(), nullable=True),
    sa.Column('draft', sa.Boolean(), nullable=True),
    sa.Column('message_delivered', sa.Boolean(), nullable=True),
    sa.Column('message_read', sa.Boolean(), nullable=True),
    sa.Column('date_delivery', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_send', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('blacklisted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_message')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    # ### end Alembic commands ###
