"""empty message

Revision ID: 5b84ae8ea71b
Revises: 17da34dfffc3
Create Date: 2021-11-30 18:02:25.049789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b84ae8ea71b'
down_revision = '17da34dfffc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('id_recipient', sa.Integer(), nullable=True))
    op.drop_column('message', 'id_receiver')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('id_receiver', sa.INTEGER(), nullable=True))
    op.drop_column('message', 'id_recipient')
    # ### end Alembic commands ###
