"""empty message

Revision ID: 8a31296eeb1a
Revises: 
Create Date: 2021-12-09 23:52:40.148482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a31296eeb1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft',
    sa.Column('id_draft', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('id_sender', sa.Integer(), nullable=True),
    sa.Column('recipient_json', sa.Unicode(length=128), nullable=True),
    sa.Column('date_delivery', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_draft')
    )
    op.create_table('message',
    sa.Column('id_message', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('id_sender', sa.Integer(), nullable=True),
    sa.Column('id_recipient', sa.Integer(), nullable=True),
    sa.Column('draft', sa.Boolean(), nullable=True),
    sa.Column('message_delivered', sa.Boolean(), nullable=True),
    sa.Column('message_read', sa.Boolean(), nullable=True),
    sa.Column('date_delivery', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_send', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('blacklisted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_message')
    )
    op.create_table('attachment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_message', sa.Integer(), nullable=True),
    sa.Column('id_draft', sa.Integer(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_draft'], ['draft.id_draft'], ),
    sa.ForeignKeyConstraint(['id_message'], ['message.id_message'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attachment')
    op.drop_table('message')
    op.drop_table('draft')
    # ### end Alembic commands ###
