"""empty message

Revision ID: a39f562a0870
Revises: e5baaae51d90
Create Date: 2021-12-04 09:32:10.555168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a39f562a0870'
down_revision = 'e5baaae51d90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_message', sa.Unicode(length=128), nullable=True),
    sa.Column('data', sa.Unicode(length=128), nullable=True),
    sa.ForeignKeyConstraint(['id_message'], ['message.id_message'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attachment')
    # ### end Alembic commands ###
