"""empty message

Revision ID: d3ec01718344
Revises: a39f562a0870
Create Date: 2021-12-04 10:21:05.163033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3ec01718344'
down_revision = 'a39f562a0870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachment', sa.Column('id_draft', sa.Unicode(length=128), nullable=True))
    op.create_foreign_key(None, 'attachment', 'draft', ['id_draft'], ['id_draft'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attachment', type_='foreignkey')
    op.drop_column('attachment', 'id_draft')
    # ### end Alembic commands ###
