"""empty message

Revision ID: e5baaae51d90
Revises: 5b84ae8ea71b
Create Date: 2021-12-01 00:07:13.696034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5baaae51d90'
down_revision = '5b84ae8ea71b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft',
    sa.Column('id_draft', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.Unicode(length=128), nullable=True),
    sa.Column('id_sender', sa.Integer(), nullable=True),
    sa.Column('recipient_json', sa.Unicode(length=128), nullable=True),
    sa.Column('date_delivery', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_draft')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('draft')
    # ### end Alembic commands ###
