openapi: 3.0.1
info:
  title: Messages Service API
  description: Messages Microservice of Message in a Bottle Application
  version: "0.1"
servers:
- url: /
paths:
  /messages:
    get:
      tags:
      - Message
      description: Get all messages list
      operationId: mib_resources_message_get_all_messages
      parameters:
      - name: type
        in: query
        description: The types of messages to retrieve
        required: true
        style: form
        explode: true
        schema:
          type: string
          enum:
          - sent
          - received
      responses:
        "200":
          description: Return messages list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message'
                x-content-type: application/json
        default:
          description: An error occured during retrieving the list
      x-openapi-router-controller: swagger_server.controllers.message_controller
    post:
      tags:
      - Message
      summary: Send a new message
      operationId: mib_resources_message_send_message
      requestBody:
        description: Create a new message and send it
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message_post'
        required: true
      responses:
        "201":
          description: Message sent
        default:
          description: Error processing the message
      x-openapi-router-controller: swagger_server.controllers.message_controller
  /messages/{message_id}:
    get:
      tags:
      - Message
      description: Get a message by its id
      operationId: mib_resources_message_get_message
      parameters:
      - name: message_id
        in: path
        description: Message Unique ID
        required: true
        style: simple
        explode: false
        schema:
          minimum: 0
          type: integer
          format: int64
      responses:
        "200":
          description: Return message
        "404":
          description: Message not found
        default:
          description: An error occured during retrieving the message
      x-openapi-router-controller: swagger_server.controllers.message_controller
    delete:
      tags:
      - Message
      description: Delete a message by its id
      operationId: mib_resources_message_delete_message
      parameters:
      - name: message_id
        in: path
        description: Message Unique ID
        required: true
        style: simple
        explode: false
        schema:
          minimum: 0
          type: integer
          format: int64
      responses:
        "202":
          description: Message deleted
        "404":
          description: Message not found
        default:
          description: An error occured during the deletion the message
      x-openapi-router-controller: swagger_server.controllers.message_controller
  /messages/{message_id}/withdraw:
    post:
      tags:
      - Message
      description: Withdraw a sent message by its id
      operationId: mib_resources_message_withdraw_message
      parameters:
      - name: message_id
        in: path
        description: Message Unique ID
        required: true
        style: simple
        explode: false
        schema:
          minimum: 0
          type: integer
          format: int64
      responses:
        "200":
          description: Message withdrawn
        "404":
          description: Message not found
        default:
          description: Error processing the withdrawing
      x-openapi-router-controller: swagger_server.controllers.message_controller
  /drafts:
    get:
      tags:
      - Draft
      description: Get all drafts list
      operationId: mib_resources_draft_get_all_drafts
      responses:
        "200":
          description: Return drafts list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Draft'
                x-content-type: application/json
        default:
          description: An error occured during retrieving the list of drafts
      x-openapi-router-controller: swagger_server.controllers.draft_controller
    post:
      tags:
      - Draft
      summary: Create a new draft
      operationId: mib_resources_draft_save_draft
      requestBody:
        description: Create and save a new draft
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Draft_post'
        required: true
      responses:
        "201":
          description: Created
        default:
          description: Error saving the draft
      x-openapi-router-controller: swagger_server.controllers.draft_controller
  /drafts/{draft_id}:
    get:
      tags:
      - Draft
      description: Get a draft by its id
      operationId: mib_resources_draft_get_draft
      parameters:
      - name: draft_id
        in: path
        description: Draft Unique ID
        required: true
        style: simple
        explode: false
        schema:
          minimum: 0
          type: integer
          format: int64
      responses:
        "200":
          description: Return draft
        "404":
          description: Draft not found
        default:
          description: An error occured during retrieving the draft
      x-openapi-router-controller: swagger_server.controllers.draft_controller
    delete:
      tags:
      - Draft
      description: Delete a draft by its id
      operationId: mib_resources_draft_delete_draft
      parameters:
      - name: draft_id
        in: path
        description: Draft Unique ID
        required: true
        style: simple
        explode: false
        schema:
          minimum: 0
          type: integer
          format: int64
      responses:
        "202":
          description: Draft deleted
        "404":
          description: Draft not found
        default:
          description: An error occured during the deletion the draft
      x-openapi-router-controller: swagger_server.controllers.draft_controller
  /drafts/{draft_id}/send:
    post:
      tags:
      - Draft
      description: Send a draft by its id
      operationId: mib_resources_draft_send_draft
      parameters:
      - name: draft_id
        in: path
        description: Draft Unique ID
        required: true
        style: simple
        explode: false
        schema:
          minimum: 0
          type: integer
          format: int64
      responses:
        "201":
          description: Draft sent
        "404":
          description: Draft not found
        default:
          description: Error processing the draft
      x-openapi-router-controller: swagger_server.controllers.draft_controller
components:
  schemas:
    Message:
      required:
      - date_delivery
      - date_send
      - id_message
      - id_sender
      - message_delivered
      - message_read
      - recipients_list
      - text
      type: object
      properties:
        id_message:
          type: integer
          description: Message ID
          example: 0
        id_sender:
          type: integer
          description: Sender ID
          example: 1
        recipients_list:
          type: array
          description: List of recipients IDs
          items:
            example: "2, 3"
        text:
          type: string
          description: Message text
          example: "Hi, how are you ?"
        message_delivered:
          type: boolean
          description: flag for message delivery
          example: false
        message_read:
          type: boolean
          description: flag for message read
          example: false
        date_delivery:
          type: string
          description: date of delivery
          format: date
          example: 2021-11-24
        date_send:
          type: string
          description: date of send
          format: date
          example: 2021-11-23
      example:
        date_send: 2021-11-23T00:00:00.000+00:00
        id_message: 0
        date_delivery: 2021-11-24T00:00:00.000+00:00
        message_delivered: false
        message_read: false
        recipients_list:
        - "2, 3"
        - "2, 3"
        text: "Hi, how are you ?"
        id_sender: 1
    Message_post:
      required:
      - date_delivery
      - recipients_list
      - text
      type: object
      properties:
        id_sender:
          type: integer
          description: Sender ID
          example: 1
        recipients_list:
          type: array
          description: List of recipients IDs
          items:
            example: "2, 3"
        text:
          type: string
          description: Message text
          example: "Hi, how are you ?"
        date_delivery:
          type: string
          description: date of delivery
          format: date
          example: 2021-11-24
      example:
        date_delivery: 2021-11-24T00:00:00.000+00:00
        recipients_list:
        - "2, 3"
        - "2, 3"
        text: "Hi, how are you ?"
        id_sender: 1
    
    Draft:
      required:
      - date_delivery
      - date_send
      - id_message
      - id_sender
      - message_delivered
      - message_read
      - recipients_list
      - text
      type: object
      properties:
        id_message:
          type: integer
          description: Message ID
          example: 0
        id_sender:
          type: integer
          description: Sender ID
          example: 1
        recipients_list:
          type: array
          description: List of recipients IDs
          items:
            example: "2, 3"
        text:
          type: string
          description: Message text
          example: "Hi, how are you ?"
        message_delivered:
          type: boolean
          description: flag for message delivery
          example: false
        message_read:
          type: boolean
          description: flag for message read
          example: false
        date_delivery:
          type: string
          description: date of delivery
          format: date
          example: 2021-11-24
        date_send:
          type: string
          description: date of send
          format: date
          example: 2021-11-23
      example:
        date_send: 2021-11-23T00:00:00.000+00:00
        id_message: 0
        date_delivery: 2021-11-24T00:00:00.000+00:00
        message_delivered: false
        message_read: false
        recipients_list:
        - "2, 3"
        - "2, 3"
        text: "Hi, how are you ?"
        id_sender: 1

    Draft_post:
      required:
      - text
      type: object
      properties:
        id_sender:
          type: integer
          description: Sender ID
          example: 1
        recipients_list:
          type: array
          description: List of recipients IDs
          items:
            example: "2, 3"
        text:
          type: string
          description: Message text
          example: "Hi, how are you ?"
        date_delivery:
          type: string
          description: date of delivery
          format: date
          example: 2021-11-24
      example:
        date_delivery: 2021-11-24T00:00:00.000+00:00
        recipients_list:
        - "2, 3"
        - "2, 3"
        text: "Hi, how are you ?"
        id_sender: 1